# Generated by Django 5.2.5 on 2025-08-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_dias_vacaciones_disponibles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='periodo_vacacional',
            field=models.CharField(choices=[('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029')], default='2025-2026', help_text='Período vacacional al que corresponde la solicitud', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='tipo_vacaciones',
            field=models.CharField(choices=[('regulares', 'Regulares'), ('adelantadas', 'Adelantadas'), ('fraccionadas', 'Fraccionadas')], default='regulares', help_text='Tipo de vacaciones según la antigüedad del empleado', max_length=20),
        ),
    ]
