# Generated by Django 5.2.5 on 2025-08-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_solicitudvacaciones_periodo_vacacional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='es_rrhh',
            field=models.BooleanField(default=False, help_text='Indica si este empleado es parte del departamento de RRHH'),
        ),
    ]
