# Generated by Django 5.2.5 on 2025-08-27 16:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_empleado_es_rrhh'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudNuevoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_solicitante', models.CharField(max_length=120)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('persona_responsable', models.CharField(max_length=120)),
                ('fecha_inicio_labores', models.DateField()),
                ('grupo_ocupacional', models.CharField(choices=[('empleado', 'Empleado'), ('practicante', 'Practicante'), ('locador', 'Locador de Servicios')], max_length=20)),
                ('puesto_a_solicitud', models.CharField(max_length=120)),
                ('denominacion_puesto', models.CharField(choices=[('gerente', 'Gerente'), ('sub_gerente', 'Sub gerente'), ('jefe', 'Jefe'), ('supervisor', 'Supervisor'), ('analista', 'Analista'), ('coordinador', 'Coordinador')], max_length=20)),
                ('motivo_contratacion', models.TextField(max_length=800)),
                ('modalidad_contratacion', models.CharField(max_length=120)),
                ('tiempo_meses', models.PositiveIntegerField(help_text='Especificar tiempo (meses)', validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('observado', 'Observado')], default='pendiente', max_length=20)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('comentario_rrhh', models.TextField(blank=True, max_length=800)),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_nuevo_colaborador_procesadas', to='empleados.empleado')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_nuevo_colaborador', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Solicitud de Nuevo Colaborador',
                'verbose_name_plural': 'Solicitudes de Nuevo Colaborador',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
