# Generated by Django 5.2.5 on 2025-09-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_solicitudnuevocolaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='area',
            field=models.CharField(blank=True, help_text='Área o departamento del empleado', max_length=100, null=True),
        ),
    ]
