# Generated by Django 5.2.5 on 2025-09-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_empleado_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='gerencia',
            field=models.CharField(blank=True, choices=[('gerencia_comercial_local', 'Gerencia Comercial Local'), ('gerencia_comercial_internacional', 'Gerencia Comercial Internacional'), ('gerencia_desarrollo_organizacional', 'Gerencia de Desarrollo Organizacional'), ('gerencia_administracion_finanzas', 'Gerencia Administración y Finanzas')], help_text='Gerencia a la que pertenece el empleado', max_length=50, null=True),
        ),
    ]
