# Generated by Django 5.2.5 on 2025-09-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_empleado_gerencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='jerarquia',
            field=models.CharField(choices=[('director', 'Director'), ('gerente', 'Gerente'), ('sub_gerente', 'Sub Gerente'), ('jefe', 'Jefe'), ('supervisor', 'Supervisor'), ('coordinador', 'Coordinador'), ('asistente', 'Asistente'), ('auxiliar', 'Auxiliar')], default='auxiliar', help_text='Nivel jerárquico del empleado en la organización', max_length=20),
        ),
    ]
