# Generated by Django 5.2.5 on 2025-09-01 19:39

import empleados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0010_empleado_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='dni',
            field=models.CharField(blank=True, help_text='Documento Nacional de Identidad (8 dígitos)', max_length=8, null=True, unique=True, validators=[empleados.models.validar_dni], verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='solicitudnuevocolaborador',
            name='dni_colaborador',
            field=models.CharField(blank=True, help_text='DNI del nuevo colaborador (8 dígitos)', max_length=8, null=True, validators=[empleados.models.validar_dni], verbose_name='DNI del Colaborador'),
        ),
    ]
