# Generated by Django 5.2.5 on 2025-09-01 19:41

import empleados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0012_populate_dni_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(default='00000000', help_text='Documento Nacional de Identidad (8 dígitos)', max_length=8, unique=True, validators=[empleados.models.validar_dni], verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='solicitudnuevocolaborador',
            name='dni_colaborador',
            field=models.CharField(default='00000000', help_text='DNI del nuevo colaborador (8 dígitos)', max_length=8, validators=[empleados.models.validar_dni], verbose_name='DNI del Colaborador'),
        ),
    ]
