# Generated by Django 5.2.5 on 2025-09-02 00:32

import empleados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0013_make_dni_fields_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudnuevocolaborador',
            name='apellido_colaborador',
            field=models.CharField(default='', help_text='Apellidos del nuevo colaborador', max_length=100, verbose_name='Apellido del Colaborador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudnuevocolaborador',
            name='email_colaborador',
            field=models.EmailField(default='', help_text='Correo electrónico del nuevo colaborador', max_length=254, verbose_name='Email del Colaborador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudnuevocolaborador',
            name='nombre_colaborador',
            field=models.CharField(default='', help_text='Nombre completo del nuevo colaborador', max_length=100, verbose_name='Nombre del Colaborador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(help_text='Documento Nacional de Identidad (8 dígitos)', max_length=8, unique=True, validators=[empleados.models.validar_dni], verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='solicitudnuevocolaborador',
            name='dni_colaborador',
            field=models.CharField(help_text='DNI del nuevo colaborador (8 dígitos)', max_length=8, validators=[empleados.models.validar_dni], verbose_name='DNI del Colaborador'),
        ),
    ]
