# Generated by Django 5.2.5 on 2025-09-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0014_solicitudnuevocolaborador_apellido_colaborador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudnuevocolaborador',
            name='motivo_contratacion',
            field=models.CharField(
                choices=[
                    ('nuevo_puesto', 'Nuevo puesto de trabajo'),
                    ('reemplazo_promocion', 'Reemplazo por promoción'),
                    ('reemplazo_renuncia', 'Reemplazo por renuncia'),
                    ('reemplazo_vencimiento', 'Reemplazo por vencimiento de contrato'),
                    ('fallecimiento', 'Fallecimiento'),
                    ('otros', 'Otros'),
                ],
                help_text='Seleccione el motivo de la contratación',
                max_length=30
            ),
        ),
    ]
