# Generated by Django 5.2.5 on 2025-09-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0015_alter_solicitudnuevocolaborador_motivo_contratacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='dias_calendario_tomados_año',
            field=models.IntegerField(default=0, help_text='Días calendario ya tomados en el año actual'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='dias_vacaciones_calendario',
            field=models.IntegerField(default=42, help_text='Días calendario equivalentes (laborables + fines de semana estimados)'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fines_semana_incluidos_año',
            field=models.IntegerField(default=0, help_text='Cantidad de fines de semana incluidos en vacaciones del año'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dias_vacaciones_disponibles',
            field=models.IntegerField(default=20, help_text='Días laborables de vacaciones por período'),
        ),
    ]
