# Generated by Django 5.2.5 on 2025-09-22 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0016_empleado_dias_calendario_tomados_año_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dir_subordinados', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='gerente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ger_subordinados', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefe_subordinados', to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dias_vacaciones_disponibles',
            field=models.IntegerField(default=30, help_text='Días laborables de vacaciones por período'),
        ),
    ]
